/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_EAF_FILES           2
#define MMAP_EAF_CHECKSUM        0x56F4

enum MMAP_EAF_LISTS {
    MMAP_EAF_BEAUTY_EAF = 0,        /*!< beauty.eaf */
    MMAP_EAF_RUN_EAF = 1,        /*!< run.eaf */
};
